# Generated by Django 5.1.3 on 2024-12-06 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_profile_image_alter_appuser_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=100)),
                ('image', models.URLField(help_text='Help Santa find this present!')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='accounts.profile')),
            ],
        ),
    ]
