# Generated by Django 5.1.3 on 2024-12-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='present',
            name='user',
        ),
    ]
