# Generated by Django 5.1.1 on 2024-12-08 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='image',
            field=models.URLField(help_text='Help Santa identify this present!'),
        ),
        migrations.AlterField(
            model_name='present',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to=settings.AUTH_USER_MODEL),
        ),
    ]
