# Generated by Django 5.1.1 on 2024-12-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presents', '0002_alter_present_image_alter_present_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
